### ISSUE TITLE
ITMS-90713: Missing Info.plist value - A value for the Info.plist key 'CFBundleIconName' is missing in the bundle

### ISSUE THREAD

**Issue by LeoJHarris** [jfversluis/DifferentAppIconsSample#1]
Hi @jfversluis I got this working in my app for debug for two separate app configurations that need to be deployed to their own app store listing with unique bundle identifier and app icons but when I submit to app store I get `ITMS-90713: Missing Info.plist value`

On iOS I have say both: 
- InfoA.plist
- InfoB.plist

Ive already added `CFBundleIconName` into the InfoA.plist file which makes me wonder which which info.plist file its looking into.

That being said I removed the original "Info.plist" so when submitting build on iOS error occurs about missing "Info.plist" value. Is it still looking for the "Info.plist" file that I removed because in your example you provide LogicalName with "Info.plist" but in my case how can I have two manifest/plist files with their own unique CFBundleIdentifier if they still reference the same Info.plist in the LogicalName.

```csharp
None Include="Info.plist" Condition=" '$(Configuration)' == 'Debug' " />
  <None Include="Info-Production.plist" Condition=" '$(Configuration)' == 'Release' ">
    <LogicalName>Info.plist</LogicalName>
  </None>
``` 

No matter what I do even after checking other info.plist files in other projects I cannot get around this issue which I think has to do with the multiple info.plist manifest files.

```csharp
We identified one or more issues with a recent delivery for your app, "XXXXX" 1.0.6 (1.0). Please correct the following issues, then upload again.

ITMS-90713: Missing Info.plist value - A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'XXXXXXX'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7.
```

**Comment by jfversluis** [comment]
But it says it misses that one key, that implies that the `info.plist` file is actually included. 

Does the `Info-Production.plist` file actually contain the `CFBundleIconName` key?

**Comment by LeoJHarris** [comment]
@jfversluis That would make sense if it says its missing that one key then its using the info.plist file I have used for the build configuration. This is how I have setup the project below with the Info.plist files.

![Capture](https://user-images.githubusercontent.com/5468757/114688242-a4160c00-9d68-11eb-81cc-de38998eedd9.PNG)

![Capture1](https://user-images.githubusercontent.com/5468757/114688247-a5dfcf80-9d68-11eb-9889-490f95acdf67.PNG)

**Comment by LeoJHarris** [comment]
@jfversluis I thought maybe due to the use of two info.plist files per build configuration it has introduced an issue with the missing info.plist value? I couldn't get my head around why it was missing the value with it definitely being in the file as shown above.

**Comment by jfversluis** [comment]
Definitely weird, I've never run into this. It should just include the file like you, if you build the right configuration and the key is in there. I guess the only thing you can do to trace this down is to go step by step. Build, inspect your obj folder for the configuration you're building and see if the info.plist is in there and it's the one you expect. If yes, build an ipa and extract that and see if the right info.plist is still in there, etc.

**Comment by LeoJHarris** [comment]
@jfversluis okay Ill check that.

**Comment by LeoJHarris** [comment]
@jfversluis got this working now, not entirely sure how but working now after fiddling around. Thanks!

**Comment by jfversluis** [comment]
Glad you made it work!
